name: Build and Netlify Deploy On Release
on:
  push:
    branches:
      - release
jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.16.0"

      - name: Install dependencies
        run: npm install

      - name: Install Netlify CLI
        run: npm i -g netlify-cli

      - name: Build and Release
        run: npm run release
